version: '3.1'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: desafio_db
    ports:
      - 5432:5432
